//! Rust counterparts to TypeScript `key-impls.test.ts`.
//! Derivation outputs are pinned to vectors generated by the TypeScript sources.

use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use majik_key::*;
use serde_json::Value;
use std::sync::OnceLock;

fn vectors() -> &'static Value {
    static VECTORS: OnceLock<Value> = OnceLock::new();
    VECTORS.get_or_init(|| serde_json::from_str(include_str!("vectors/ts-vectors.json")).unwrap())
}

fn string(value: &Value) -> &str {
    value.as_str().unwrap()
}

#[test]
fn derive_matches_typescript_vectors_for_every_implemented_algorithm() {
    let mut count = 0;
    for mnemonic in vectors()["mnemonics"].as_array().unwrap() {
        let seed = hex::decode(string(&mnemonic["seedHex"])).unwrap();
        for (id, expected) in mnemonic["keys"].as_object().unwrap() {
            let id: KeyId = id.parse().unwrap();
            if matches!(id, KeyId::Falcon512 | KeyId::Falcon1024) {
                assert!(derive_key(id, &seed).is_err());
                continue;
            }

            let actual = derive_key(id, &seed).unwrap();
            assert_eq!(
                actual.public_key,
                B64.decode(string(&expected["pub"])).unwrap()
            );
            assert_eq!(
                &actual.secret_key[..],
                &B64.decode(string(&expected["sec"])).unwrap()[..]
            );
            count += 1;
        }
        let x25519 = derive_key(KeyId::X25519, &seed).unwrap();
        assert_eq!(
            fingerprint_from_public_raw(&x25519.public_key),
            string(&mnemonic["fingerprint"])
        );
    }
    assert!(count >= 80, "checked {count} TypeScript-pinned keypairs");
}

#[test]
fn derive_keys_is_deterministic_deduplicates_ids_and_does_not_mutate_seed() {
    let seed = hex::decode(string(&vectors()["mnemonics"][0]["seedHex"])).unwrap();
    let original = seed.clone();
    let first = derive_keys(&seed, &[KeyId::X25519, KeyId::Ed25519, KeyId::X25519]).unwrap();
    let second = derive_keys(&seed, &[KeyId::Ed25519, KeyId::X25519]).unwrap();

    assert_eq!(seed, original);
    assert_eq!(first.len(), 2);
    for id in [KeyId::X25519, KeyId::Ed25519] {
        assert_eq!(first[&id].public_key, second[&id].public_key);
        assert_eq!(&first[&id].secret_key[..], &second[&id].secret_key[..]);
    }
}

#[test]
fn derivation_rejects_invalid_seed_lengths_and_unimplemented_ids() {
    for length in [0, 32, 63, 65] {
        assert!(derive_key(KeyId::Ed25519, &vec![0; length]).is_err());
    }
    assert!(derive_keys(&[0; 64], &[KeyId::Hqc128]).is_err());
    assert!(derive_key(KeyId::Falcon512, &[0; 64]).is_err());
}
