//! # majik-key
//!
//! Pure-Rust port of the TypeScript `@majikah/majik-key` (1.x, multi-key registry):
//! every keypair of an account — X25519, Ed25519, ML-KEM, ML-DSA, SLH-DSA, BTC/ETH/SOL —
//! derived deterministically from one BIP-39 mnemonic and sealed with Argon2id + AES-256-GCM.
//!
//! Layout mirrors the TS source tree: `index.ts` → this file / `mod.rs`,
//! `majik-key.ts` → [`majik_key`], `core/**` → [`core`].
//!
//! JSON produced here is interchangeable with the TS library (camelCase fields, same
//! secret-key encodings, same KDF parameters), verified against vectors generated by the
//! TS code itself — see `tests/`.

pub mod core;
mod majik_key;

pub use crate::core::backup::{
    build_readme_text, looks_like_png, looks_like_zip, to_safe_file_name, BackupResult, BackupSeed,
    BackupSource, CreateBackupParams, MajikKeyBackup, MajikKeyBackupError, PngCodec, ToZipOptions,
    BACKUP_FORMAT_VERSION, README_TEXT,
};
pub use crate::core::crypto::constants::*;
pub use crate::core::crypto::crypto_provider::*;
pub use crate::core::crypto::wordlist::*;
pub use crate::core::database::system::identity::*;
pub use crate::core::error::*;
pub use crate::core::keys::hkdf_recipe::*;
pub use crate::core::keys::key_id::*;
pub use crate::core::keys::key_impls::*;
pub use crate::core::keys::key_store::*;
pub use crate::core::keys::keypair_handle::*;
pub use crate::core::keys::registry::*;
pub use crate::core::keys::types::*;
pub use crate::core::types::*;
pub use crate::core::validator::*;
pub use crate::core::web3::{
    bitcoin::bitcoin::*,
    bitcoin::constants::*,
    bitcoin::types::*,
    ethereum::constants::*,
    ethereum::ethereum::*,
    ethereum::types::*,
    solana::constants::*,
    solana::solana::*,
    solana::types::*,
    types::MajikKeyWeb3Namespace,
    utils::{base58_encode, base58check_encode},
};
pub use crate::majik_key::*;
